version: '3.9'

volumes:
  mongo_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  streamlyn:
    driver: bridge

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: streamlyn
    volumes:
      - mongo_data:/data/db
    networks:
      - streamlyn
    entrypoint:
      - bash
      - -c
      - |
        if [ ! -f /data/security-key ]; then
          openssl rand -base64 756 > /data/security-key
          chmod 400 /data/security-key
          chown 999:999 /data/security-key
        fi
        exec docker-entrypoint.sh "$@"
    command: "mongod --bind_ip_all --replSet rs0 --keyFile /data/security-key"

  mongo-setup:
    image: mongo:8.0
    container_name: mongo-setup
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - streamlyn
    depends_on:
      - mongo
    volumes:
      - $PWD/.docker/mongo/init.sh:/scripts/init.sh
    restart: on-failure
    entrypoint: [ "/bin/bash", "/scripts/init.sh" ]

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    networks:
      - streamlyn
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: streamlyn
      MINIO_ROOT_PASSWORD: streamlyn
      MINIO_BUCKETS: "streamlyn"
    command: server /data --console-address ":9001"

  minio_setup:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    depends_on:
      - minio
    restart: on-failure
    networks:
      - streamlyn
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set dockerminio http://minio:9000 streamlyn streamlyn;
      /usr/bin/mc mb dockerminio/streamlyn;
      exit 0;
      "

  redis:
    image: redis:7.4.6-alpine
    container_name: redis
    networks:
      - streamlyn
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  redisinsight:
    image: redis/redisinsight:2.70
    container_name: redisinsight
    networks:
      - streamlyn
    ports:
      - "5540:5540"
    environment:
      RI_REDIS_HOST: redis


