spring:
  cloud:
    config:
      enabled: false
    aws:
      credentials:
        access-key: streamlyn
        secret-key: streamlyn
      region:
        static: ${AWS_REGION:us-east-1}
      s3:
        bucket: ${OBJECT_STORAGE_BUCKET:streamlyn}
        endpoint: ${OBJECT_STORAGE_ENDPOINT:http://localhost:9000}
        path-style-access-enabled: true