spring:
  application:
    name: StreamlynApi

tus:
  max-size: ${TUS_MAX_SIZE:1073741824}

object-storage:
  tmp-dir: ${OBJECT_STORAGE_TMP_DIR:/tmp}
  output-dir: ${OBJECT_STORAGE_OUTPUT_DIR:/uploads}


